### ISSUE TITLE
Remove all non-ascii chars in source

### ISSUE THREAD

**Issue by dhowe** [dhowe/ritajs#110]
Currently any browser pages with rita will fail if they don't use: ` <meta charset="utf-8">` because (I believe) of non-ascii characters in the source code. Please check this and make sure it doesn't fail w'out that tag.

You can test it with a file like this:

```
<html>
<head>
  <!-- meta charset="utf-8"-->
  <script src="../dist/rita.js"></script>
</head>
<body>Test</body>
</html>
```
![Screenshot 2021-01-16 at 6 45 17 PM](https://user-images.githubusercontent.com/737638/104809842-3ae73100-582b-11eb-8ca5-adaab2d62a9c.png)

**Comment by dhowe** [comment]
I'm still seeing the same error in the current build:

![Uploading image.png…]()

**Comment by Real-John-Cheung** [comment]
status: need to check the libraries that might contain non-ascii characters 10/2/21

**Comment by Real-John-Cheung** [comment]
I checked all the source code used to build, they all contain just ascii characters
I think the unicode characters (in source code marked as `\uxxxx`) are translated to non ascii characters in the output
(those characters can be found in antlr4/util, he, and riscriptparser)

**Comment by Real-John-Cheung** [comment]
using webpack-terser-plugin @ 2.x seems to be able to fix it...
https://github.com/Real-John-Cheung/rita2js/blob/issue%23110/config/webpack.asciionly.js 
the output file has only ascii character, but not tested

**Comment by dhowe** [comment]
cool -- pls test with the simple example above

**Comment by dhowe** [comment]
We may need to change the options for tercer/webpack.
- [ ] tercer makes the files bigger  (not by a lot but some, ~5%)
- [ ] I also see some warnings in the webpack stats.json file (see below)

```
       "optimizationBailout": [
          "ModuleConcatenation bailout: Module is not an ECMAScript module"
        ],
```

**Comment by Real-John-Cheung** [comment]
the file being bigger might due to a escaped string (e.g `\u05C0`, 6byte) is  bigger than a utf8 character ( `׀` is 2byte)?

**Comment by dhowe** [comment]
ok for now
