### ISSUE TITLE
RiMarkov fromJSON function not working

### ISSUE THREAD

**Issue by Litleck** [dhowe/ritajs#120]
What happens is if you use `toJSON()` on the current data and store it, then try to reuse that by calling `RiMarkov.fromJSON(data)`, it doesn't actually restore the data. What happens is it returns the RiMarkov object but its input property is undefined, which then leads to `addText()` failing because it tries to push the text to the input property, but that won't work since its undefined.

Also for a feature request I would much prefer that the `toJSON` and `fromJSON` functions used objects instead of a string.

**Comment by dhowe** [comment]
Hi @Litleck  sorry I've only just seen this (not sure how I missed the notification). Anyhow there was indeed a bug specifically with the 'input' field in the markov object. It should be fixed as of 2.4.71. If you have a moment to retest, you can go ahead and close this if it looks ok.

**Comment by Litleck** [comment]
It seems to have fixed it but the method of converting it to JSON has made my database so large that there's a 3 - 4 second delay to getting the data. In the past I've used a markov library that can convert to JSON its able to do so while using little space. With a 1.1MB text file of newline seperated strings and converting that to JSON with an n-size of 3 results in a text file of 26 MB. I may be wrong but I feel like the previous version was able to convert it to JSON more efficiently.

**Comment by dhowe** [comment]
Thanks for the report back @Litleck. If you are not using the `maxLengthMatch` option, you can reduce the JSON size  with the disableInputChecks option:

`let rm = new RiMarkov(3, { disableInputChecks: true });`

Give this a try and let me know how it affects the JSON size.

Explanation: the current default behavior of the model is NEVER to output a string of N tokens that is sequentially present in the input (this is sort of "overfitting" in ML terms). So the `maxLengthMatch` option species the maximum length that you will tolerate. If you don't care about any of this, and don't mind getting some of the input copied into the output, then you can disable it via the option above.

FYI, this is relatively new design decision based on my own usage of the tools (I _never_ want long sequences of input copied into my outputs), but it may not be appropriate as a default as it does add extra size to the model to allow such checking. So if you have feedback on this let me know...

**Comment by dhowe** [comment]
> Also passing an array to addText results in RangeError: Maximum call stack size exceeded

I can't recreate this  -- can you include a minimal test here that shows the problem ?

**Comment by Litleck** [comment]
> Thanks for the report back @Litleck. If you are not using the `maxLengthMatch` option, you can reduce the JSON size  with the `disableInputChecks` option:
> 
> `let rm = new RiMarkov(3, { disableInputChecks: true });`
> 
> Give this a try and let me know how it affects the JSON size.
> 
> Explanation: the current default behavior of the model is NEVER to output a string of N tokens that is sequentially present in the input (this is sort of "overfitting" in ML terms). So the `maxLengthMatch` option species the maximum length that you will tolerate. If you don't care about any of this, and don't mind getting some of the input copied into the output, then you can disable it via the option above.
> 
> FYI, this is relatively new design decision based on my own usage of the tools (I _never_ want long sequences of input copied into my outputs), but it may not be appropriate as a default as it does add extra size to the model to allow such checking. So if you have feedback on this let me know...
> 

A main issue I was having with other libraries was getting repeats of input data which led me to RiTa.  Near the end of the data is a ton of repeated `{}`
Not sure if its related to the functionality but could be wasted space.

For the RangeError basically a text file full of newline separated strings, 1.1MB in this case and use fs to read and convert it to an array. Then run addText with that array.

**Comment by dhowe** [comment]
> For the RangeError basically a text file full of newline separated strings, 1.1MB in this case and use fs to read and convert it to an array. Then run addText with that array.

Do you mind sharing the file? (you can zip it and post it here, or, if you'd rather send it to me via email)

**Comment by dhowe** [comment]
> A main issue I was having with other libraries was getting repeats of input data which led me to RiTa. Near the end of the data is a ton of repeated {}
> Not sure if its related to the functionality but could be wasted space.

So I'm using [flatted](https://www.npmjs.com/package/flatted) to serialize the cyclical structure of the markov tree, so it is not meant to be straight JSON or to be human-readable. Another options would be to come up with a custom JSON (or other) format which is not cyclical and possibly smaller. But this is relatively low on the priority list (unless someone else wants to help with it)

**Comment by Litleck** [comment]
> > For the RangeError basically a text file full of newline separated strings, 1.1MB in this case and use fs to read and convert it to an array. Then run addText with that array.
> 
> Do you mind sharing the file and/or your test ? (you can zip it and post it here, or, if you'd rather send it to me via email)

Could I send it by email if that's okay with you?



> > A main issue I was having with other libraries was getting repeats of input data which led me to RiTa. Near the end of the data is a ton of repeated {}. Not sure if its related to the functionality but could be wasted space.
> 
> So I'm using [flatted](https://www.npmjs.com/package/flatted) to serialize the cyclical structure of the markov tree, so it is not meant to be straight JSON or to be human-readable.
> 
> Another option would be to come up with a custom JSON (or other) format which is not cyclical and possibly smaller. But this is relatively low on the priority list (unless someone else wants to help with it)

I understand. I would try to help but markov chains are the one thing I just cannot understand.

**Comment by dhowe** [comment]
Closing (feel free to reopen if there are further questions)
