### ISSUE TITLE
Pulling latest release via Github API fails

### ISSUE THREAD

**Issue by msawired** [dhowe/ritajs#130]
Hello from OpenProcessing!

We feature Ritajs in our list of default libraries, however we are having some issues pulling the latest releases from Github API. 
[https://api.github.com/repos/dhowe/RiTaJS/releases/latest](https://api.github.com/repos/dhowe/RiTaJS/releases/latest) returns empty, as opposed to other libraries we use. https://api.github.com/repos/dhowe/RiTaJS/releases/ also returns only your beta releases, ignores the recent.
Your releases seems to be in order on the Github website, so I couldn't tell what was wrong. Do you know any attribute in your releases that may prevent them to be displayed in the call above?

**Comment by dhowe** [comment]
Hi @msawired - thanks for the note. Can you tell me what test you are running so that I can troubleshoot ? FYI, we've just updated the library internally to use es6 imports. Of course this shouldn't affect the output format, but apparently it may have :/

**Comment by dhowe** [comment]
@msawired - any feedback on this?

**Comment by msawired** [comment]
Sorry about the late reply, not sure why I wasn't receiving notifications on this.

Yes, it is sort of the only way we can keep up with the releases. Basically, we are checking new releases every day to save its meta on our db to allow users to choose the version on the website. Once the sketches are saved, we make sure the sketches use that version instead of the latest, to prevent potential incompatibility.  
We definitely do not need beta releases, so it is fine if you wanna keep the github releases to only stable version to prevent the headache. Cheers!

**Comment by dhowe** [comment]
How about the new github packages? Does that work for you as well ?

**Comment by msawired** [comment]
Doesn't seem straight forward but I can take a look. Can you release a test package for me to try?

**Comment by dhowe** [comment]
Actually I've found a route for automating releases -- see if this one works for you: https://github.com/dhowe/ritajs/releases/tag/v2.4.82

**Comment by msawired** [comment]
Yes, this works! thank you for all the help, @dhowe. Cheers!
