### ISSUE TITLE
Highlightjs bugs

### ISSUE THREAD

**Issue by dhowe** [dhowe/ritajs#133]
Problems with RiScript highlighter (at least the one [here](https://observablehq.com/@dhowe/riscript))

- [ ] appears to be also highlighting JS keywords (*in*, *from* in first image -- intermittent)
- [x] not correctly handling nested parens (second image)

![Screenshot 2021-03-01 at 2 05 03 AM](https://user-images.githubusercontent.com/737638/109428584-9c0d4180-7a32-11eb-8568-d98be06b596d.png)

![image](https://user-images.githubusercontent.com/737638/109429661-daf1c600-7a37-11eb-849c-2cf2990c2f24.png)

**Comment by Real-John-Cheung** [comment]
For problem 1
<img width="543" alt="螢幕截圖 2021-03-01 下午11 22 34" src="https://user-images.githubusercontent.com/61215358/109518232-041c6000-7ae5-11eb-9463-219c0f262edd.png">
seems that it doesn't occur on my machine...
problem 2 is now fixed 
<img width="637" alt="螢幕截圖 2021-03-01 下午11 29 59" src="https://user-images.githubusercontent.com/61215358/109519273-0cc16600-7ae6-11eb-8295-ff6128a3c754.png">

**Comment by dhowe** [comment]
as mentioned, problem 1 is intermittent -- it only happens in some cells
I will try to recreate
