### ISSUE TITLE
randomWord returning same word if pos option passed

### ISSUE THREAD

**Issue by kentskyo** [dhowe/ritajs#164]
RiTa.randomWord({ pos: "nns"}) returns the same word over and over...

**Comment by Real-John-Cheung** [comment]
@kentskyo thanks for the message
@dhowe I think that's because we are now just return the first found word, will change it and add tests for that

**Comment by dhowe** [comment]
fixed in 52c20aa32708, @Real-John-Cheung  can you add tests?

**Comment by dhowe** [comment]
@Real-John-Cheung please close this if done

**Comment by Real-John-Cheung** [comment]
done
