### ISSUE TITLE
randomWord for pos: "rp" returns undefined

### ISSUE THREAD

**Issue by kentskyo** [dhowe/ritajs#167]
while RiTa.search({pos:"rp"}) returns elements
RiTa.randomWord({pos:"rp"}) returns undefined

**Comment by dhowe** [comment]
- [x] implement fix in js
- [x] add test in js
- [ ] sync fix/tests with Java

**Comment by dhowe** [comment]
thanks for the bug report, @kentskyo 
the fix will be in the next release
as you've probably realized the temporary workaround is to use RiTa.search() as follows:

`let randWord = RiTa.search({ pos: "rp", shuffle: true })[0];`

**Comment by dhowe** [comment]
status @Real-John-Cheung  ?
