### ISSUE TITLE
RiTa.pos("lancer") returns ReferenceError: Arrays is not defined

### ISSUE THREAD

**Issue by kentskyo** [dhowe/ritajs#179]
thought this was curious...

**Comment by dhowe** [comment]
@Real-John-Cheung I've committed a fix for this, please:

- [ ] add tests for 'lancer' and 'builder' and anything else not properly tested
- [ ] check code in java and add tests in java

**Comment by dhowe** [comment]
this should be fixed in 2.4.103, now available on npm

**Comment by dhowe** [comment]
@Real-John-Cheung please close this if done

**Comment by Real-John-Cheung** [comment]
done
