### ISSUE TITLE
syllables() breaks in version 2.6.1 when it encounters digits

### ISSUE THREAD

**Issue by shadoof** [dhowe/ritajs#204]
current behavior:
RiTa.syllables("(1903)") -> Error: Invalid phoneme: w-ah-n
(tokenizes and ? then fails to analyze a digit-by-digit  'pronunciation')

desired behavior:
either:
- ignore and just return digits (as for punctuation tokens) or
- return syllables for the digits as they would be pronounced (implies being able to recognize dates, times, etc.)

**Comment by dhowe** [comment]
fixed
