### ISSUE TITLE
26: Uncaught ReferenceError: RiTa is not defined when including Rita in p5 IDE

### ISSUE THREAD

**Issue by indefinit** [dhowe/RiTaJS#24]
A number of my students have been reporting this issue with the latest p5 IDE and both the minified Rita.js as well as rita-full.js

It seems like they are including the script tag in the html head as intended but are still running into the error.  Have you run into this before?  Thanks!

**Comment by dhowe** [comment]
thanks @indefinit  -- let me take a look

**Comment by dhowe** [comment]
I can't recreate this problem (after trying on two separate machines). Can you give some more info (version, os, etc)?

<img width="746" alt="screen shot 2016-03-30 at 5 11 33 pm" src="https://cloud.githubusercontent.com/assets/737638/14137495/9f11ce44-f69a-11e5-931f-194f52c3f4b5.png">

**Comment by indefinit** [comment]
closing this as it turns out it was user error.  thanks for looking into this though!
