### ISSUE TITLE
New examples for various platforms

### ISSUE THREAD

**Issue by cqx931** [dhowe/ritajs#41]
Based on the old ritajs readme file
Shall we create a new wiki page for these?

#### A simple sketch
--------
Create a new file on your desktop called 'test.html' and download the latest rita.js from [here](http://rednoise.org/rita/download/rita.js), add the following lines, save and drag it into a browser:

```html
<html>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="./rita.js"></script>
  <script>
    window.onload = function() {
      let words = RiTa.tokenize("The elephant took a bite!");
      $('#content').text(words);
    };
  </script>
  <div id="content" width=200 height=200></div>
<html>
```

#### With [node.js](http://nodejs.org/) and [npm](https://www.npmjs.com/)
--------
To install: `$ npm install rita`

```javascript
let rita = require('rita');
let features = rita.analyze("The elephant took a bite!");
console.log(features);
```

#### With [p5.js](http://p5js.org/)
--------
Create a new file on your desktop called 'test.html' and download the latest rita.js from [here](http://rednoise.org/rita/download/rita.min.js), add the following lines, save and drag it into a browser:

```html
<html>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.3/p5.min.js"></script>
  <script src="./rita.js"></script>
  <script>
  function setup() {

    createCanvas(200,200);
    background(50);
    textSize(20);
    noStroke();

    let words = RiTa.tokenize("The elephant took a bite!")
    for (let i=0; i < words.length; i++) {
        text(words[i], 50, 50 + i*20);
    }
  }
  </script>
</html>
```

#### With [browserify](http://browserify.org/) and [npm](https://www.npmjs.com/)
--------
Install [browserify](https://www.npmjs.com/package/browserify) (if you haven't already)
```
$ sudo npm install -g browserify
```
Create a file called 'main.js' with the following code:
```java
require('rita');

let features = RiTa.analyze("The elephant took a bite!");
console.log(features);
```
Now install RiTa
```
$ npm install rita
```
Now use browserify to pack all the required modules into bundle.js
```
$ browserify main.js -o bundle.js
```
Create create a file called 'test.html' with a single script tag as below, then open it in a web browser and check the output in the 'Web Console'
```html
<script src="bundle.js"></script>
```

#### With [processing.js](http://processingjs.org)
--------
Create a new file on your desktop called 'test.html' and download the latest rita.js from [here](http://rednoise.org/rita/download/rita.min.js), add the following lines, save and drag it into a browser:

```html
<html>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/processing.js/1.4.8/processing.min.js"></script>
  <script src="./rita.js"></script>
  <script type="text/processing" data-processing-target="processing-canvas">
    void setup() {

      size(200,200);
      background(50);
      textSize(20);
      noStroke();

      String words = RiTa.tokenize("The elephant took a bite!");
      for (int i=0; i < words.length; i++) {
          text(words[i], 50, 50 + i*20);
      }
    }
  </script>
  <canvas id="processing-canvas"> </canvas>
</html>
```

**Comment by dhowe** [comment]
>  Shall we create a new wiki page for these?
Yes, sounds good
