### ISSUE TITLE
Repeat behavior in Choice sequences

### ISSUE THREAD

**Issue by Real-John-Cheung** [dhowe/ritajs#63]
In
`src/visitor.js` line382

**Comment by dhowe** [comment]
no-repeat should be the default for choices -- to allow repeat add a new allowRepeats() transform ?

**Comment by dhowe** [comment]
this causes problems for weighted choices where the user WANTS the output with higher weight to repeat. 
Options:
1. leave as is
2. use non-repeating only for those options without weight

Note that this is implemented in the 'default-choice-random' branches in all 3 repos
