### ISSUE TITLE
test multiple characters strings in RiTa test Should correctly call isPunctuation

### ISSUE THREAD

**Issue by Real-John-Cheung** [dhowe/ritajs#68]
In
`test/rita-tests.js` line149 and line160

**Comment by dhowe** [comment]
I don't understand what this means... what was the full comment in the code?

**Comment by Real-John-Cheung** [comment]
<img width="543" alt="螢幕截圖 2021-03-22 下午8 44 38" src="https://user-images.githubusercontent.com/61215358/111991572-6d751900-8b4f-11eb-8997-a10ab0e704ed.png">
