### ISSUE TITLE
Verify escape sequence for dollar sign

### ISSUE THREAD

**Issue by dhowe** [dhowe/ritajs#80]
Make sure we can show literal dollar signs in RiTa.evaluate by using `&#36;`

**Comment by Real-John-Cheung** [comment]
we can show dollar signs, but showing contents like "This is $100" needs some extra steps
`let raw = RiTa.evaluate("This is &#36 100", {}); -> raw: "This is $ 100" `
`let result = raw.replace(/(\$) (\d+)/g, '$1$2'); -> result: "This is $100"`
If directly use this `RiTa.evaluate("This is &#36100", {});` will return `This is  
贄`

**Comment by dhowe** [comment]
hmmm, good catch. we need to figure out a solution for this
